STATION_REGION_MAP = {
    "ANC": "West",
    "ATL": "South",
    "AUS": "South",
    "BNA": "South",
    "BOS": "Northeast",
    "BWI": "South",
    "CLE": "Midwest",
    "CLT": "South",
    "CMH": "Midwest",
    "DAL": "South",
    "DEN": "West",
    "DFW": "South",
    "DTW": "Midwest",
    "EWR": "Northeast",
    "HNL": "West",
    "HOU": "South",
    "IAD": "South",
    "IAH": "South",
    "IND": "Midwest",
    "JAX": "South",
    "JFK": "Northeast",
    "LAS": "West",
    "LAX": "West",
    "LGA": "Northeast",
    "MCI": "Midwest",
    "MCO": "South",
    "MDW": "Midwest",
    "MEM": "South",
    "MIA": "South",
    "MSP": "Midwest",
    "MSY": "South",
    "OAK": "West",
    "OGG": "West",
    "OKC": "South",
    "OMA": "Midwest",
    "ORD": "Midwest",
    "PDX": "West",
    "PHL": "Northeast",
    "PHX": "West",
    "PIT": "Northeast",
    "RDU": "South",
    "SAN": "West",
    "SAT": "South",
    "SEA": "West",
    "SFO": "West",
    "SJC": "West",
    "SLC": "West",
    "SMF": "West",
    "STL": "Midwest",
    "TPA": "South",
}


def station_region(station: str) -> str:
    return STATION_REGION_MAP.get(str(station).upper(), "Unknown")
